package com.example.dao;

import com.example.model.UserAuthority;
import com.example.model.example.UserAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    int countByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    int deleteByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    int insert(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    int insertSelective(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    List<UserAuthority> selectByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    UserAuthority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserAuthority record, @Param("example") UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    int updateByExample(@Param("record") UserAuthority record, @Param("example") UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    int updateByPrimaryKeySelective(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    int updateByPrimaryKey(UserAuthority record);
}