package com.example.model;

import java.util.Date;

public class UserAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authority.id
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authority.user_id
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authority.auth_id
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    private String authId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authority.create_time
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authority.modify_time
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authority.create_operator
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    private String createOperator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authority.id
     *
     * @return the value of user_authority.id
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authority.id
     *
     * @param id the value for user_authority.id
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authority.user_id
     *
     * @return the value of user_authority.user_id
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authority.user_id
     *
     * @param userId the value for user_authority.user_id
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authority.auth_id
     *
     * @return the value of user_authority.auth_id
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authority.auth_id
     *
     * @param authId the value for user_authority.auth_id
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public void setAuthId(String authId) {
        this.authId = authId == null ? null : authId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authority.create_time
     *
     * @return the value of user_authority.create_time
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authority.create_time
     *
     * @param createTime the value for user_authority.create_time
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authority.modify_time
     *
     * @return the value of user_authority.modify_time
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authority.modify_time
     *
     * @param modifyTime the value for user_authority.modify_time
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authority.create_operator
     *
     * @return the value of user_authority.create_operator
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authority.create_operator
     *
     * @param createOperator the value for user_authority.create_operator
     *
     * @mbggenerated Mon Jun 18 12:08:40 CST 2018
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }
}